#!/usr/bin/env node
// Generated by pnpm providers:sync. Edit the canonical source in skills/ instead.
import { main } from '../install-support.mjs';
await main('codex').catch(error => { console.error(error.message); process.exitCode = 1; });
