#!/usr/bin/env node

/**
 * Projects the two canonical skills under `skills/**` into the four provider
 * trees under `providers/**`.
 *
 * Adapted from the consumer repository's mixed `scripts/agents-sync/sync.mjs`,
 * reduced to the migration projection it owned. What it keeps is the part that
 * was load-bearing: strict frontmatter validation, symlink rejection on both
 * the canonical and the output side, path containment, duplicate-output
 * detection, two-phase atomic writes, and deletion that is permitted only for
 * paths the *previous* manifest owned. What it drops is everything that was
 * about the consumer's own agents, standards, OpenCode base configuration and
 * generated CI workflow.
 *
 * The one behavioral difference from the original is the reason this phase
 * exists: a provider tree receives skill documents and references only. The
 * engine is one versioned package every adapter installs, so copying
 * `packages/migration-engine/src/**` into four provider trees -- which is what
 * the consumer generator did -- is now a generation error, not a feature.
 */

import { randomUUID } from "node:crypto";
import {
  lstat,
  mkdir,
  open,
  readFile,
  readdir,
  rename,
  rm,
  rmdir,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

const defaultRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
/** The canonical source root. Nothing outside it is read as a skill. */
const canonicalRoot = "skills";
const generatedNotice =
  "Generated by pnpm providers:sync. Edit the canonical source in skills/ instead.";
/**
 * Committed record of every file this synchronizer owns. It is the ONLY thing
 * that may be deleted on sync; unrelated files under `providers/` are left
 * alone, which is what makes an adapter able to carry hand-authored files
 * (installers, READMEs) beside its generated ones.
 */
export const manifestPath = "providers/generated-files.json";

const canonicalNamePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const skillLimits = { name: 64, description: 1024, compatibility: 500 };

/**
 * Release identity is injected while packaging an already committed tree, so no
 * committed file may contain it. Templates carry these placeholders instead and
 * the packaging phase renders them; `providers:check` compares the templates,
 * never a rendered artifact.
 */
export const ENGINE_MCP_ENTRY_PLACEHOLDER = "{{ENGINE_MCP_ENTRY}}";
export const TOOLKIT_VERSION_PLACEHOLDER = "{{TOOLKIT_VERSION}}";
export const TOOLKIT_COMMIT_PLACEHOLDER = "{{TOOLKIT_COMMIT}}";
export const TOOLKIT_CONTENT_HASH_PLACEHOLDER = "{{TOOLKIT_CONTENT_HASH}}";

/** The MCP server name every provider registers, unchanged from the consumer. */
const MCP_SERVER_NAME = "start-migration";

/**
 * Engine source must never reach a provider tree. Checked by extension at
 * generation time rather than only in a test: the test proves the committed
 * tree is clean, this refuses to make it dirty in the first place.
 */
const ENGINE_SOURCE_SUFFIXES = [".mjs", ".cjs", ".js", ".ts", ".mts", ".cts"];

const resolveInsideRoot = (root, relativePath) => {
  const resolved = path.resolve(root, relativePath);
  if (!resolved.startsWith(`${root}${path.sep}`)) {
    throw new Error(`Path escapes the repository: ${relativePath}`);
  }
  return resolved;
};

const addOutput = (outputs, relativePath, content) => {
  if (outputs.has(relativePath)) {
    throw new Error(`Duplicate generated path: ${relativePath}`);
  }
  outputs.set(relativePath, Buffer.from(content));
};

const validateName = (name, expectedName) => {
  if (
    name !== expectedName ||
    !canonicalNamePattern.test(name) ||
    name.length > skillLimits.name
  ) {
    throw new Error(`Skill file/name mismatch: ${expectedName}`);
  }
};

const validateSkillMetadata = (name, metadata) => {
  if (typeof metadata.description !== "string" || !metadata.description.trim()) {
    throw new Error(`Skill has no description: ${name}`);
  }
  if (metadata.description.length > skillLimits.description) {
    throw new Error(`Skill description is too long: ${name}`);
  }
  if (
    metadata.compatibility !== undefined &&
    (typeof metadata.compatibility !== "string" ||
      metadata.compatibility.length > skillLimits.compatibility)
  ) {
    throw new Error(`Skill has invalid compatibility: ${name}`);
  }
  for (const field of ["license", "allowed-tools"]) {
    if (metadata[field] !== undefined && typeof metadata[field] !== "string") {
      throw new Error(`Skill ${field} must be a string: ${name}`);
    }
  }
  if (
    metadata.metadata !== undefined &&
    (!metadata.metadata ||
      typeof metadata.metadata !== "object" ||
      Array.isArray(metadata.metadata) ||
      Object.values(metadata.metadata).some(
        (value) => typeof value !== "string",
      ))
  ) {
    throw new Error(`Skill metadata values must be strings: ${name}`);
  }
  for (const field of ["disable-model-invocation", "user-invocable"]) {
    if (metadata[field] !== undefined && typeof metadata[field] !== "boolean") {
      throw new Error(`Skill ${field} must be boolean: ${name}`);
    }
  }
  for (const legacy of ["disableModelInvocation", "userInvocable"]) {
    if (metadata[legacy] !== undefined) {
      throw new Error(
        `Skill uses unsupported camelCase field ${legacy}: ${name}`,
      );
    }
  }
};

const parseDocument = (content, sourcePath) => {
  const match = content.match(
    /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/,
  );
  if (!match) throw new Error(`${sourcePath} is missing YAML frontmatter`);
  const metadata = parseYaml(match[1]);
  if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) {
    throw new Error(`${sourcePath} frontmatter must be a YAML mapping`);
  }
  if (typeof metadata.description === "string") {
    metadata.description = metadata.description.trim();
  }
  return { metadata, body: match[2].trim() };
};

const renderYaml = (value) => stringifyYaml(value, { lineWidth: 0 }).trimEnd();

const renderDocument = (metadata, body, sourcePath) =>
  `---\n${renderYaml(metadata)}\n---\n\n<!-- ${generatedNotice} Source: ${sourcePath}. -->\n\n${body.trim()}\n`;

const renderJson = (value) => `${JSON.stringify(value, null, 2)}\n`;

const inspectCanonicalPath = async (root, relativePath) => {
  const normalized = relativePath.replaceAll(path.sep, "/");
  let current = root;
  let currentRelative = "";
  for (const segment of normalized.split("/").filter(Boolean)) {
    current = path.join(current, segment);
    currentRelative = path.posix.join(currentRelative, segment);
    if ((await lstat(current)).isSymbolicLink()) {
      throw new Error(
        `Canonical sources cannot be symlinks: ${currentRelative}`,
      );
    }
  }
};

const readCanonicalFile = async (root, relativePath, encoding) => {
  await inspectCanonicalPath(root, relativePath);
  return readFile(resolveInsideRoot(root, relativePath), encoding);
};

const listSkillNames = async (root) => {
  await inspectCanonicalPath(root, canonicalRoot);
  const entries = await readdir(resolveInsideRoot(root, canonicalRoot), {
    withFileTypes: true,
  });
  const linked = entries.find((entry) => entry.isSymbolicLink());
  if (linked) {
    throw new Error(
      `Canonical sources cannot be symlinks: ${canonicalRoot}/${linked.name}`,
    );
  }
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
};

/**
 * Install output, never a canonical source. Under pnpm these are symlinks that
 * must be neither walked nor copied, and `skills/**` is a workspace location a
 * future skill-local install could still land in.
 */
const installArtifacts = new Set(["node_modules"]);

const walkFiles = async (root, relativePath) => {
  await inspectCanonicalPath(root, relativePath);
  const absolute = resolveInsideRoot(root, relativePath);
  const entries = await readdir(absolute, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    if (installArtifacts.has(entry.name)) continue;
    const child = path.posix.join(
      relativePath.replaceAll(path.sep, "/"),
      entry.name,
    );
    if (entry.isDirectory()) files.push(...(await walkFiles(root, child)));
    else if (entry.isSymbolicLink()) {
      throw new Error(`Canonical sources cannot be symlinks: ${child}`);
    } else files.push(child);
  }
  return files;
};

const pick = (source, keys) =>
  Object.fromEntries(
    keys
      .filter((key) => source?.[key] !== undefined)
      .map((key) => [key, source[key]]),
  );

/** Fields every provider's skill format accepts. */
const commonSkillMetadata = (metadata) =>
  pick(metadata, [
    "name",
    "description",
    "license",
    "compatibility",
    "metadata",
    "allowed-tools",
  ]);

const wrapperBody = (skill, appended) =>
  `Load and follow the \`${skill}\` skill. ${appended}`;

const FORWARD_ARGUMENTS =
  "Use this command input as its invocation arguments: $ARGUMENTS";
const FORWARD_APPENDED =
  "Treat any text appended to this prompt invocation as the skill arguments.";

/**
 * The four approved providers. Unknown targets are rejected simply by not being
 * here: `providerNames` is the closed set every caller validates against.
 *
 * `metadata` lists the provider-specific frontmatter keys the target supports
 * beyond the common set. Only Claude has native invocation flags, which is also
 * why only Claude needs no wrapper: its skill is directly user-invocable.
 */
const providers = [
  {
    name: "claude",
    metadata: ["context", "agent", "disable-model-invocation", "user-invocable"],
    mcp: {
      output: "providers/claude/.mcp.json",
      render: (server) => renderJson({ mcpServers: { [MCP_SERVER_NAME]: server } }),
    },
    install: {
      mechanism: "plugin-marketplace",
      // The plugin root is assigned by the host at install time, so there is no
      // skill path to record -- recording a guess is how an installer ends up
      // writing outside what the host manages.
      skillRoot: { user: null, project: null },
      mcpConfig: { user: null, project: null },
    },
  },
  {
    name: "codex",
    wrapper: (skill, description) => ({
      output: `providers/codex/prompts/${skill}.md`,
      metadata: { description },
      body: wrapperBody(skill, FORWARD_ARGUMENTS),
    }),
    mcp: {
      output: "providers/codex/config.toml",
      render: (server) =>
        `# ${generatedNotice}\n\n[mcp_servers.${MCP_SERVER_NAME}]\ncommand = ${JSON.stringify(server.command)}\nargs = ${JSON.stringify(server.args)}\n`,
    },
    install: {
      mechanism: "agent-skills-directory",
      skillRoot: { user: "~/.agents/skills", project: ".agents/skills" },
      mcpConfig: { user: "~/.codex/config.toml", project: ".codex/config.toml" },
    },
  },
  {
    name: "opencode",
    wrapper: (skill, description) => ({
      output: `providers/opencode/commands/${skill}.md`,
      metadata: { description },
      body: wrapperBody(skill, FORWARD_ARGUMENTS),
    }),
    mcp: {
      // A fragment, not a config: OpenCode's `opencode.json` is consumer-owned
      // and carries unrelated settings the adapter merges into, never replaces.
      output: "providers/opencode/opencode.fragment.json",
      render: (server) =>
        renderJson({
          mcp: {
            [MCP_SERVER_NAME]: {
              type: "local",
              command: [server.command, ...server.args],
              enabled: true,
            },
          },
        }),
    },
    install: {
      mechanism: "agent-skills-directory",
      skillRoot: {
        user: "~/.config/opencode/skills",
        project: ".opencode/skills",
      },
      mcpConfig: {
        user: "~/.config/opencode/opencode.json",
        project: "opencode.json",
      },
    },
  },
  {
    name: "copilot",
    wrapper: (skill, description) => ({
      output: `providers/copilot/prompts/${skill}.prompt.md`,
      metadata: { mode: "agent", description },
      body: wrapperBody(skill, FORWARD_APPENDED),
    }),
    mcp: {
      output: "providers/copilot/mcp.json",
      render: (server) =>
        renderJson({ servers: { [MCP_SERVER_NAME]: { type: "stdio", ...server } } }),
    },
    install: {
      // Repository scope only. Copilot documents no user-global or marketplace
      // skill root, and inventing one is how an installer writes somewhere the
      // host will never read.
      mechanism: "repository-archive",
      skillRoot: { user: null, project: ".github/skills" },
      mcpConfig: { user: null, project: ".vscode/mcp.json" },
    },
  },
];

/**
 * The closed provider set. This is how an unknown target is rejected: there is
 * no option, environment variable, or manifest field that selects a provider, so
 * `providers` above is the only place one can exist. A validator would be a
 * second answer to a question with one authority.
 */
export const providerNames = providers.map((provider) => provider.name);

const skillRootFor = (provider) => `providers/${provider}/skills`;

/**
 * The MCP launch every adapter renders at packaging time.
 *
 * The entry point is a placeholder, not a path: the engine lives wherever the
 * adapter installed it, which is not knowable from a committed template and is
 * never derived from the consumer's working directory. That is the whole reason
 * the consumer's registration -- a literal `node <consumer>/.agents/skills/
 * <skill>/scripts/mcp-server.mjs` -- does not survive extraction. Written split
 * so a repository-wide scan for that literal stays a clean gate rather than one
 * with a carve-out for the file that explains it.
 */
const mcpServerTemplate = () => ({
  command: "node",
  args: [ENGINE_MCP_ENTRY_PLACEHOLDER],
});

/**
 * Packaging and installation metadata, with release identity left unrendered.
 *
 * One file per adapter rather than a packaging framework: an adapter needs to
 * know which files it owns, where its skills install, and which engine release
 * it pins. Everything else is the installer's business in a later phase.
 */
const adapterManifest = (provider, skillNames, outputs) => ({
  name: `artifact-migration-tools-${provider.name}`,
  provider: provider.name,
  toolkit: {
    name: "artifact-migration-tools",
    version: TOOLKIT_VERSION_PLACEHOLDER,
    commit: TOOLKIT_COMMIT_PLACEHOLDER,
    contentHash: TOOLKIT_CONTENT_HASH_PLACEHOLDER,
  },
  engine: {
    package: "@artifact-migration-tools/migration-engine",
    version: TOOLKIT_VERSION_PLACEHOLDER,
    mcpEntry: ENGINE_MCP_ENTRY_PLACEHOLDER,
  },
  skills: skillNames,
  // Where this adapter's host supports installing, per the provider's own
  // documentation. `null` means the provider documents no such scope; an
  // installer must refuse it rather than pick somewhere plausible.
  install: provider.install,
  mcpTemplate: path.posix.relative(
    `providers/${provider.name}`,
    provider.mcp.output,
  ),
  files: outputs
    .filter((relative) => relative !== `providers/${provider.name}/adapter.json`)
    .map((relative) => path.posix.relative(`providers/${provider.name}`, relative))
    .sort(),
});

const buildOutputs = async (root, outputs) => {
  const skillNames = await listSkillNames(root);
  if (!skillNames.length) {
    throw new Error(`No canonical skills found under ${canonicalRoot}/`);
  }

  /** provider name -> its generated paths, for that provider's manifest. */
  const perProvider = new Map(providers.map((p) => [p.name, []]));
  const emit = (provider, relativePath, content) => {
    addOutput(outputs, relativePath, content);
    perProvider.get(provider).push(relativePath);
  };

  for (const skillName of skillNames) {
    const sourcePath = `${canonicalRoot}/${skillName}/SKILL.md`;
    const parsed = parseDocument(
      await readCanonicalFile(root, sourcePath, "utf8"),
      sourcePath,
    );
    validateName(parsed.metadata.name, skillName);
    validateSkillMetadata(skillName, parsed.metadata);

    for (const provider of providers) {
      const metadata = commonSkillMetadata(parsed.metadata);
      Object.assign(metadata, pick(parsed.metadata, provider.metadata ?? []));
      emit(
        provider.name,
        path.posix.join(skillRootFor(provider.name), skillName, "SKILL.md"),
        renderDocument(metadata, parsed.body, sourcePath),
      );
    }

    // Claude's skill is directly user-invocable, so a wrapper would be a second
    // entry point to the same document. The other three need one command each.
    if (parsed.metadata["user-invocable"] === true) {
      for (const provider of providers.filter((item) => item.wrapper)) {
        const wrapper = provider.wrapper(skillName, parsed.metadata.description);
        emit(
          provider.name,
          wrapper.output,
          renderDocument(wrapper.metadata, wrapper.body, sourcePath),
        );
      }
    }

    for (const resource of await walkFiles(
      root,
      `${canonicalRoot}/${skillName}`,
    )) {
      const relative = path.posix.relative(
        `${canonicalRoot}/${skillName}`,
        resource,
      );
      if (relative === "SKILL.md") continue;
      // The Phase 2 boundary, enforced at the point of copying. An adapter
      // installs the one engine package; a provider tree that carried engine
      // modules is what produced four implementations to keep in step.
      if (ENGINE_SOURCE_SUFFIXES.some((suffix) => relative.endsWith(suffix))) {
        throw new Error(
          `Engine source may not be projected into a provider tree: ${resource}`,
        );
      }
      const content = await readCanonicalFile(root, resource);
      for (const provider of providers) {
        emit(
          provider.name,
          path.posix.join(skillRootFor(provider.name), skillName, relative),
          content,
        );
      }
    }
  }

  const server = mcpServerTemplate();
  for (const provider of providers) {
    emit(provider.name, provider.mcp.output, provider.mcp.render(server));
    emit(provider.name, `providers/${provider.name}/install.mjs`,
      `#!/usr/bin/env node\n// ${generatedNotice}\nimport { main } from '../install-support.mjs';\nawait main('${provider.name}').catch(error => { console.error(error.message); process.exitCode = 1; });\n`);
  }
  for (const provider of providers) {
    emit(
      provider.name,
      `providers/${provider.name}/adapter.json`,
      renderJson(
        adapterManifest(provider, skillNames, perProvider.get(provider.name)),
      ),
    );
  }
};

const renderManifest = (outputs) =>
  `${JSON.stringify([...outputs.keys()].sort(), null, 2)}\n`;

const readManifest = async (root) => {
  try {
    const parsed = JSON.parse(
      await readFile(resolveInsideRoot(root, manifestPath), "utf8"),
    );
    if (
      !Array.isArray(parsed) ||
      parsed.some(
        (entry) =>
          typeof entry !== "string" ||
          path.isAbsolute(entry) ||
          entry === ".." ||
          entry.startsWith("../") ||
          path.posix.normalize(entry) !== entry,
      ) ||
      new Set(parsed).size !== parsed.length
    ) {
      throw new Error(`Invalid generated files manifest: ${manifestPath}`);
    }
    parsed.forEach((entry) => resolveInsideRoot(root, entry));
    return parsed;
  } catch (error) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
};

const validateOutputTarget = async (root, relativePath) => {
  const segments = relativePath.split("/");
  let current = root;
  for (const [index, segment] of segments.entries()) {
    const isTarget = index === segments.length - 1;
    current = path.join(current, segment);
    try {
      const stats = await lstat(current);
      if (stats.isSymbolicLink()) {
        throw new Error(`Generated file path is a symlink: ${relativePath}`);
      }
      if (isTarget && stats.isDirectory()) {
        throw new Error(`Generated file path is a directory: ${relativePath}`);
      }
      if (!isTarget && !stats.isDirectory()) {
        throw new Error(
          `Generated file parent is not a directory: ${relativePath}`,
        );
      }
    } catch (error) {
      if (error?.code === "ENOENT") return;
      throw error;
    }
  }
};

const validateOutputTargets = async (root, outputs, previous = []) => {
  for (const relativePath of [
    ...new Set([...outputs.keys(), ...previous, manifestPath]),
  ]) {
    await validateOutputTarget(root, relativePath);
  }
};

const stageAtomicWrite = async (absolute, content) => {
  const temp = path.join(
    path.dirname(absolute),
    `.providers-sync-${randomUUID()}.tmp`,
  );
  let handle;
  try {
    handle = await open(temp, "wx");
    await handle.writeFile(content);
    await handle.close();
    return [temp, absolute];
  } catch (error) {
    if (handle) {
      await handle.close().catch(() => {});
      await rm(temp, { force: true });
    }
    throw error;
  }
};

const check = async (root, outputs) => {
  const previous = await readManifest(root);
  await validateOutputTargets(root, outputs, previous);
  const expectedKeys = new Set(outputs.keys());
  const differences = [];
  for (const [relativePath, expected] of outputs) {
    try {
      const actual = await readFile(resolveInsideRoot(root, relativePath));
      if (!actual.equals(expected)) differences.push(`CHANGED ${relativePath}`);
    } catch (error) {
      if (error?.code === "ENOENT" || error?.code === "EISDIR")
        differences.push(`MISSING ${relativePath}`);
      else throw error;
    }
  }
  try {
    const committed = await readFile(
      resolveInsideRoot(root, manifestPath),
      "utf8",
    );
    if (committed !== renderManifest(outputs))
      differences.push(`CHANGED ${manifestPath}`);
  } catch (error) {
    if (error?.code === "ENOENT") differences.push(`MISSING ${manifestPath}`);
    else throw error;
  }
  for (const relativePath of previous) {
    if (expectedKeys.has(relativePath)) continue;
    try {
      await readFile(resolveInsideRoot(root, relativePath));
      differences.push(`STALE ${relativePath}`);
    } catch (error) {
      if (error?.code !== "ENOENT" && error?.code !== "EISDIR") throw error;
    }
  }
  return differences.sort();
};

const sync = async (root, outputs) => {
  const previous = await readManifest(root);
  await validateOutputTargets(root, outputs, previous);
  const expectedKeys = new Set(outputs.keys());

  // Phase 1: stage every output as a temp file next to its destination.
  const staged = [];
  try {
    for (const [relativePath, content] of [...outputs].sort(([left], [right]) =>
      left.localeCompare(right),
    )) {
      const absolute = resolveInsideRoot(root, relativePath);
      await mkdir(path.dirname(absolute), { recursive: true });
      staged.push(await stageAtomicWrite(absolute, content));
    }
  } catch (error) {
    await Promise.all(staged.map(([temp]) => rm(temp, { force: true })));
    throw error;
  }
  // Phase 2: atomically rename each staged file into place.
  try {
    for (const [temp, absolute] of staged) await rename(temp, absolute);
  } catch (error) {
    await Promise.all(staged.map(([temp]) => rm(temp, { force: true })));
    throw error;
  }
  // Phase 3: delete only paths the previous manifest owned and we no longer
  // emit, then prune any directories left empty by those deletions.
  for (const relativePath of previous) {
    if (expectedKeys.has(relativePath)) continue;
    await rm(resolveInsideRoot(root, relativePath), { force: true });
    let parent = path.posix.dirname(relativePath);
    while (parent && parent !== ".") {
      try {
        await rmdir(resolveInsideRoot(root, parent));
      } catch {
        break; // non-empty, missing, or otherwise not ours to remove
      }
      parent = path.posix.dirname(parent);
    }
  }
  // Phase 4: record the new ownership set last.
  const manifestAbsolute = resolveInsideRoot(root, manifestPath);
  await mkdir(path.dirname(manifestAbsolute), { recursive: true });
  const [manifestTemp] = await stageAtomicWrite(
    manifestAbsolute,
    renderManifest(outputs),
  );
  try {
    await rename(manifestTemp, manifestAbsolute);
  } catch (error) {
    await rm(manifestTemp, { force: true });
    throw error;
  }

  console.log(`Synchronized ${outputs.size} generated provider files.`);
};

export const runProvidersSync = async ({
  root: targetRoot = defaultRoot,
  checkOnly = false,
} = {}) => {
  const root = path.resolve(targetRoot);
  const outputs = new Map();
  await buildOutputs(root, outputs);
  if (checkOnly) {
    return { count: outputs.size, differences: await check(root, outputs) };
  }
  await sync(root, outputs);
  return { count: outputs.size };
};

const parseCliOptions = (args) => {
  let checkOnly = false;
  for (const argument of args) {
    if (argument === "--check") checkOnly = true;
    else throw new Error(`Unknown argument: ${argument}`);
  }
  return { checkOnly };
};

const reportCheck = (count, differences) => {
  if (differences.length) {
    console.error("Generated provider files are out of date:");
    differences.forEach((difference) => console.error(`- ${difference}`));
    console.error("Run `pnpm providers:sync` and commit the result.");
    process.exitCode = 1;
  } else {
    console.log(`Provider outputs are synchronized (${count} files).`);
  }
};

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const options = parseCliOptions(process.argv.slice(2));
    const result = await runProvidersSync(options);
    if (options.checkOnly) reportCheck(result.count, result.differences);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
